require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Me::NotesController do

  # This should return the minimal set of attributes required to create a valid
  # Me::Note. As you add validations to Me::Note, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Me::NotesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all me_notes as @me_notes" do
      note = Me::Note.create! valid_attributes
      get :index, {}, valid_session
      assigns(:me_notes).should eq([note])
    end
  end

  describe "GET show" do
    it "assigns the requested me_note as @me_note" do
      note = Me::Note.create! valid_attributes
      get :show, {:id => note.to_param}, valid_session
      assigns(:me_note).should eq(note)
    end
  end

  describe "GET new" do
    it "assigns a new me_note as @me_note" do
      get :new, {}, valid_session
      assigns(:me_note).should be_a_new(Me::Note)
    end
  end

  describe "GET edit" do
    it "assigns the requested me_note as @me_note" do
      note = Me::Note.create! valid_attributes
      get :edit, {:id => note.to_param}, valid_session
      assigns(:me_note).should eq(note)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Me::Note" do
        expect {
          post :create, {:me_note => valid_attributes}, valid_session
        }.to change(Me::Note, :count).by(1)
      end

      it "assigns a newly created me_note as @me_note" do
        post :create, {:me_note => valid_attributes}, valid_session
        assigns(:me_note).should be_a(Me::Note)
        assigns(:me_note).should be_persisted
      end

      it "redirects to the created me_note" do
        post :create, {:me_note => valid_attributes}, valid_session
        response.should redirect_to(Me::Note.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved me_note as @me_note" do
        # Trigger the behavior that occurs when invalid params are submitted
        Me::Note.any_instance.stub(:save).and_return(false)
        post :create, {:me_note => {  }}, valid_session
        assigns(:me_note).should be_a_new(Me::Note)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Me::Note.any_instance.stub(:save).and_return(false)
        post :create, {:me_note => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested me_note" do
        note = Me::Note.create! valid_attributes
        # Assuming there are no other me_notes in the database, this
        # specifies that the Me::Note created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Me::Note.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => note.to_param, :me_note => { "these" => "params" }}, valid_session
      end

      it "assigns the requested me_note as @me_note" do
        note = Me::Note.create! valid_attributes
        put :update, {:id => note.to_param, :me_note => valid_attributes}, valid_session
        assigns(:me_note).should eq(note)
      end

      it "redirects to the me_note" do
        note = Me::Note.create! valid_attributes
        put :update, {:id => note.to_param, :me_note => valid_attributes}, valid_session
        response.should redirect_to(note)
      end
    end

    describe "with invalid params" do
      it "assigns the me_note as @me_note" do
        note = Me::Note.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Me::Note.any_instance.stub(:save).and_return(false)
        put :update, {:id => note.to_param, :me_note => {  }}, valid_session
        assigns(:me_note).should eq(note)
      end

      it "re-renders the 'edit' template" do
        note = Me::Note.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Me::Note.any_instance.stub(:save).and_return(false)
        put :update, {:id => note.to_param, :me_note => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested me_note" do
      note = Me::Note.create! valid_attributes
      expect {
        delete :destroy, {:id => note.to_param}, valid_session
      }.to change(Me::Note, :count).by(-1)
    end

    it "redirects to the me_notes list" do
      note = Me::Note.create! valid_attributes
      delete :destroy, {:id => note.to_param}, valid_session
      response.should redirect_to(me_notes_url)
    end
  end

end
