require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Me::NotificationsController do

  # This should return the minimal set of attributes required to create a valid
  # Me::Notification. As you add validations to Me::Notification, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Me::NotificationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all me_notifications as @me_notifications" do
      notification = Me::Notification.create! valid_attributes
      get :index, {}, valid_session
      assigns(:me_notifications).should eq([notification])
    end
  end

  describe "GET show" do
    it "assigns the requested me_notification as @me_notification" do
      notification = Me::Notification.create! valid_attributes
      get :show, {:id => notification.to_param}, valid_session
      assigns(:me_notification).should eq(notification)
    end
  end

  describe "GET new" do
    it "assigns a new me_notification as @me_notification" do
      get :new, {}, valid_session
      assigns(:me_notification).should be_a_new(Me::Notification)
    end
  end

  describe "GET edit" do
    it "assigns the requested me_notification as @me_notification" do
      notification = Me::Notification.create! valid_attributes
      get :edit, {:id => notification.to_param}, valid_session
      assigns(:me_notification).should eq(notification)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Me::Notification" do
        expect {
          post :create, {:me_notification => valid_attributes}, valid_session
        }.to change(Me::Notification, :count).by(1)
      end

      it "assigns a newly created me_notification as @me_notification" do
        post :create, {:me_notification => valid_attributes}, valid_session
        assigns(:me_notification).should be_a(Me::Notification)
        assigns(:me_notification).should be_persisted
      end

      it "redirects to the created me_notification" do
        post :create, {:me_notification => valid_attributes}, valid_session
        response.should redirect_to(Me::Notification.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved me_notification as @me_notification" do
        # Trigger the behavior that occurs when invalid params are submitted
        Me::Notification.any_instance.stub(:save).and_return(false)
        post :create, {:me_notification => {  }}, valid_session
        assigns(:me_notification).should be_a_new(Me::Notification)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Me::Notification.any_instance.stub(:save).and_return(false)
        post :create, {:me_notification => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested me_notification" do
        notification = Me::Notification.create! valid_attributes
        # Assuming there are no other me_notifications in the database, this
        # specifies that the Me::Notification created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Me::Notification.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => notification.to_param, :me_notification => { "these" => "params" }}, valid_session
      end

      it "assigns the requested me_notification as @me_notification" do
        notification = Me::Notification.create! valid_attributes
        put :update, {:id => notification.to_param, :me_notification => valid_attributes}, valid_session
        assigns(:me_notification).should eq(notification)
      end

      it "redirects to the me_notification" do
        notification = Me::Notification.create! valid_attributes
        put :update, {:id => notification.to_param, :me_notification => valid_attributes}, valid_session
        response.should redirect_to(notification)
      end
    end

    describe "with invalid params" do
      it "assigns the me_notification as @me_notification" do
        notification = Me::Notification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Me::Notification.any_instance.stub(:save).and_return(false)
        put :update, {:id => notification.to_param, :me_notification => {  }}, valid_session
        assigns(:me_notification).should eq(notification)
      end

      it "re-renders the 'edit' template" do
        notification = Me::Notification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Me::Notification.any_instance.stub(:save).and_return(false)
        put :update, {:id => notification.to_param, :me_notification => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested me_notification" do
      notification = Me::Notification.create! valid_attributes
      expect {
        delete :destroy, {:id => notification.to_param}, valid_session
      }.to change(Me::Notification, :count).by(-1)
    end

    it "redirects to the me_notifications list" do
      notification = Me::Notification.create! valid_attributes
      delete :destroy, {:id => notification.to_param}, valid_session
      response.should redirect_to(me_notifications_url)
    end
  end

end
