require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Me::PlansController do

  # This should return the minimal set of attributes required to create a valid
  # Me::Plan. As you add validations to Me::Plan, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Me::PlansController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all me_plans as @me_plans" do
      plan = Me::Plan.create! valid_attributes
      get :index, {}, valid_session
      assigns(:me_plans).should eq([plan])
    end
  end

  describe "GET show" do
    it "assigns the requested me_plan as @me_plan" do
      plan = Me::Plan.create! valid_attributes
      get :show, {:id => plan.to_param}, valid_session
      assigns(:me_plan).should eq(plan)
    end
  end

  describe "GET new" do
    it "assigns a new me_plan as @me_plan" do
      get :new, {}, valid_session
      assigns(:me_plan).should be_a_new(Me::Plan)
    end
  end

  describe "GET edit" do
    it "assigns the requested me_plan as @me_plan" do
      plan = Me::Plan.create! valid_attributes
      get :edit, {:id => plan.to_param}, valid_session
      assigns(:me_plan).should eq(plan)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Me::Plan" do
        expect {
          post :create, {:me_plan => valid_attributes}, valid_session
        }.to change(Me::Plan, :count).by(1)
      end

      it "assigns a newly created me_plan as @me_plan" do
        post :create, {:me_plan => valid_attributes}, valid_session
        assigns(:me_plan).should be_a(Me::Plan)
        assigns(:me_plan).should be_persisted
      end

      it "redirects to the created me_plan" do
        post :create, {:me_plan => valid_attributes}, valid_session
        response.should redirect_to(Me::Plan.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved me_plan as @me_plan" do
        # Trigger the behavior that occurs when invalid params are submitted
        Me::Plan.any_instance.stub(:save).and_return(false)
        post :create, {:me_plan => {  }}, valid_session
        assigns(:me_plan).should be_a_new(Me::Plan)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Me::Plan.any_instance.stub(:save).and_return(false)
        post :create, {:me_plan => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested me_plan" do
        plan = Me::Plan.create! valid_attributes
        # Assuming there are no other me_plans in the database, this
        # specifies that the Me::Plan created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Me::Plan.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => plan.to_param, :me_plan => { "these" => "params" }}, valid_session
      end

      it "assigns the requested me_plan as @me_plan" do
        plan = Me::Plan.create! valid_attributes
        put :update, {:id => plan.to_param, :me_plan => valid_attributes}, valid_session
        assigns(:me_plan).should eq(plan)
      end

      it "redirects to the me_plan" do
        plan = Me::Plan.create! valid_attributes
        put :update, {:id => plan.to_param, :me_plan => valid_attributes}, valid_session
        response.should redirect_to(plan)
      end
    end

    describe "with invalid params" do
      it "assigns the me_plan as @me_plan" do
        plan = Me::Plan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Me::Plan.any_instance.stub(:save).and_return(false)
        put :update, {:id => plan.to_param, :me_plan => {  }}, valid_session
        assigns(:me_plan).should eq(plan)
      end

      it "re-renders the 'edit' template" do
        plan = Me::Plan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Me::Plan.any_instance.stub(:save).and_return(false)
        put :update, {:id => plan.to_param, :me_plan => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested me_plan" do
      plan = Me::Plan.create! valid_attributes
      expect {
        delete :destroy, {:id => plan.to_param}, valid_session
      }.to change(Me::Plan, :count).by(-1)
    end

    it "redirects to the me_plans list" do
      plan = Me::Plan.create! valid_attributes
      delete :destroy, {:id => plan.to_param}, valid_session
      response.should redirect_to(me_plans_url)
    end
  end

end
