require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Me::SchoolClassesController do

  # This should return the minimal set of attributes required to create a valid
  # Me::SchoolClass. As you add validations to Me::SchoolClass, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Me::SchoolClassesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all me_school_classes as @me_school_classes" do
      school_class = Me::SchoolClass.create! valid_attributes
      get :index, {}, valid_session
      assigns(:me_school_classes).should eq([school_class])
    end
  end

  describe "GET show" do
    it "assigns the requested me_school_class as @me_school_class" do
      school_class = Me::SchoolClass.create! valid_attributes
      get :show, {:id => school_class.to_param}, valid_session
      assigns(:me_school_class).should eq(school_class)
    end
  end

  describe "GET new" do
    it "assigns a new me_school_class as @me_school_class" do
      get :new, {}, valid_session
      assigns(:me_school_class).should be_a_new(Me::SchoolClass)
    end
  end

  describe "GET edit" do
    it "assigns the requested me_school_class as @me_school_class" do
      school_class = Me::SchoolClass.create! valid_attributes
      get :edit, {:id => school_class.to_param}, valid_session
      assigns(:me_school_class).should eq(school_class)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Me::SchoolClass" do
        expect {
          post :create, {:me_school_class => valid_attributes}, valid_session
        }.to change(Me::SchoolClass, :count).by(1)
      end

      it "assigns a newly created me_school_class as @me_school_class" do
        post :create, {:me_school_class => valid_attributes}, valid_session
        assigns(:me_school_class).should be_a(Me::SchoolClass)
        assigns(:me_school_class).should be_persisted
      end

      it "redirects to the created me_school_class" do
        post :create, {:me_school_class => valid_attributes}, valid_session
        response.should redirect_to(Me::SchoolClass.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved me_school_class as @me_school_class" do
        # Trigger the behavior that occurs when invalid params are submitted
        Me::SchoolClass.any_instance.stub(:save).and_return(false)
        post :create, {:me_school_class => {  }}, valid_session
        assigns(:me_school_class).should be_a_new(Me::SchoolClass)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Me::SchoolClass.any_instance.stub(:save).and_return(false)
        post :create, {:me_school_class => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested me_school_class" do
        school_class = Me::SchoolClass.create! valid_attributes
        # Assuming there are no other me_school_classes in the database, this
        # specifies that the Me::SchoolClass created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Me::SchoolClass.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => school_class.to_param, :me_school_class => { "these" => "params" }}, valid_session
      end

      it "assigns the requested me_school_class as @me_school_class" do
        school_class = Me::SchoolClass.create! valid_attributes
        put :update, {:id => school_class.to_param, :me_school_class => valid_attributes}, valid_session
        assigns(:me_school_class).should eq(school_class)
      end

      it "redirects to the me_school_class" do
        school_class = Me::SchoolClass.create! valid_attributes
        put :update, {:id => school_class.to_param, :me_school_class => valid_attributes}, valid_session
        response.should redirect_to(school_class)
      end
    end

    describe "with invalid params" do
      it "assigns the me_school_class as @me_school_class" do
        school_class = Me::SchoolClass.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Me::SchoolClass.any_instance.stub(:save).and_return(false)
        put :update, {:id => school_class.to_param, :me_school_class => {  }}, valid_session
        assigns(:me_school_class).should eq(school_class)
      end

      it "re-renders the 'edit' template" do
        school_class = Me::SchoolClass.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Me::SchoolClass.any_instance.stub(:save).and_return(false)
        put :update, {:id => school_class.to_param, :me_school_class => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested me_school_class" do
      school_class = Me::SchoolClass.create! valid_attributes
      expect {
        delete :destroy, {:id => school_class.to_param}, valid_session
      }.to change(Me::SchoolClass, :count).by(-1)
    end

    it "redirects to the me_school_classes list" do
      school_class = Me::SchoolClass.create! valid_attributes
      delete :destroy, {:id => school_class.to_param}, valid_session
      response.should redirect_to(me_school_classes_url)
    end
  end

end
