#encoding: utf-8
grades:
  学前教育:
    - 大班
    - 中班
    - 小班
  小学:
    - 小学一年级
    - 小学二年级
    - 小学三年级
    - 小学四年级
    - 小学五年级
    - 小学六年级
  初中:
    - 初中一年级
    - 初中二年级
    - 初中三年级
  高中:
    - 高中一年级
    - 高中二年级
    - 高中三年级
  大学:
    - 大学一年级
    - 大学二年级
    - 大学三年级
    - 大学四年级
  职业教育:
    - 教师
    - 公务员
    - 出国留学
    
subjects: 
  学前教育:
    - 舞蹈
    - 音乐
    - 美术
    - 语言
  小学:
    - 语文
    - 数学
  初中:
    - 语文
    - 数学
    - 外语
    - 物理
    - 化学
    - 历史
    - 政治
    - 地理
  高中:
    - 语文
    - 数学
    - 外语
    - 物理
    - 化学
    - 历史
    - 政治
    - 地理
  大学:
    - 计算机
    - 金融
    - 电子信息工程
    - 农业
    - 法学
  职业教育:
    - 计算机
    - 会计
    - 财务
    - 外语
    - 
post:
    note: 'note'
    bookmark: 'bookmark'
    video: 'video'
    audio: 'audio'
    document: 'document'
    album: 'album'
